"""Domain ports (Protocols) for the AI Correlation Layer.

All infrastructure adapters must satisfy these structural subtypes.
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from ai_correlation.domain.entities.correlation_session import CorrelationSession
from ai_correlation.domain.entities.evidence_cluster import EvidenceCluster
from ai_correlation.domain.value_objects.prioritized_exposure import PrioritizedExposure
from ai_correlation.domain.value_objects.ranked_attack_path import RankedAttackPath
from ai_correlation.domain.value_objects.remediation_plan import RemediationPlan


@runtime_checkable
class CorrelationRepository(Protocol):
    """Persistence port — PostgreSQL sessions and clusters."""

    async def save_session(self, session: CorrelationSession) -> None: ...
    async def update_session(self, session: CorrelationSession) -> None: ...
    async def get_session(self, session_id: str) -> CorrelationSession | None: ...
    async def save_cluster(self, cluster: EvidenceCluster) -> None: ...
    async def list_clusters(self, tenant_id: str, session_id: str | None = None) -> list[EvidenceCluster]: ...


@runtime_checkable
class CorrelationCache(Protocol):
    """Cache port — Redis TTL cache for correlation results."""

    async def get_clusters(self, tenant_id: str) -> list[EvidenceCluster] | None: ...
    async def set_clusters(self, tenant_id: str, clusters: list[EvidenceCluster]) -> None: ...
    async def get_ranked_paths(self, tenant_id: str) -> list[RankedAttackPath] | None: ...
    async def set_ranked_paths(self, tenant_id: str, paths: list[RankedAttackPath]) -> None: ...
    async def get_prioritized(self, tenant_id: str) -> list[PrioritizedExposure] | None: ...
    async def set_prioritized(self, tenant_id: str, items: list[PrioritizedExposure]) -> None: ...
    async def get_remediation(self, cluster_id: str) -> RemediationPlan | None: ...
    async def set_remediation(self, cluster_id: str, plan: RemediationPlan) -> None: ...


@runtime_checkable
class CorrelationEventPublisher(Protocol):
    """Kafka publisher port — acl.correlation.events topic."""

    async def publish_cluster_created(self, cluster: EvidenceCluster) -> None: ...
    async def publish_paths_ranked(
        self, tenant_id: str, session_id: str, paths: list[RankedAttackPath]
    ) -> None: ...
    async def publish_exposure_prioritized(
        self, exposure: PrioritizedExposure, session_id: str
    ) -> None: ...
    async def publish_remediation_generated(self, plan: RemediationPlan, tenant_id: str, session_id: str) -> None: ...
