"""Domain ports (interfaces) for the Discovery Engine.

All infrastructure adapters must implement these protocols so the domain
and application layers stay decoupled from any I/O concern.
"""
from __future__ import annotations

import uuid
from typing import Protocol, runtime_checkable

from .entities.discovered_asset import AssetType, AssetStatus, DiscoveredAsset
from .entities.discovery_job import DiscoveryJob, JobStatus


@runtime_checkable
class DiscoveredAssetRepository(Protocol):
    async def save(self, asset: DiscoveredAsset) -> None: ...
    async def save_batch(self, assets: list[DiscoveredAsset]) -> None: ...
    async def get(self, asset_id: uuid.UUID) -> DiscoveredAsset | None: ...
    async def get_by_value(self, tenant_id: uuid.UUID, value: str) -> DiscoveredAsset | None: ...
    async def list_by_job(self, job_id: uuid.UUID) -> list[DiscoveredAsset]: ...
    async def list_by_type(
        self, tenant_id: uuid.UUID, asset_type: AssetType
    ) -> list[DiscoveredAsset]: ...
    async def update_status(self, asset_id: uuid.UUID, status: AssetStatus) -> None: ...


@runtime_checkable
class DiscoveryJobRepository(Protocol):
    async def save(self, job: DiscoveryJob) -> None: ...
    async def get(self, job_id: uuid.UUID) -> DiscoveryJob | None: ...
    async def list_by_tenant(
        self, tenant_id: uuid.UUID, limit: int = 50
    ) -> list[DiscoveryJob]: ...
    async def update_status(self, job_id: uuid.UUID, status: JobStatus) -> None: ...


@runtime_checkable
class DiscoveryEventPublisher(Protocol):
    async def publish_asset_discovered(
        self, asset: DiscoveredAsset, job: DiscoveryJob
    ) -> None: ...
    async def publish_job_completed(self, job: DiscoveryJob) -> None: ...
    async def publish_job_failed(self, job: DiscoveryJob) -> None: ...
