"""Domain ports (Protocols) for the Reporting Engine."""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from reporting.domain.entities.report import Report


@runtime_checkable
class ReportRepository(Protocol):
    async def save(self, report: Report) -> None: ...
    async def update(self, report: Report) -> None: ...
    async def get(self, report_id: str) -> Report | None: ...
    async def list_by_tenant(self, tenant_id: str, limit: int, offset: int) -> list[Report]: ...


@runtime_checkable
class EvidenceStore(Protocol):
    """Stores denormalized findings received from ACL Kafka events."""

    async def upsert_exposure(self, record: dict) -> None: ...
    async def upsert_cluster(self, record: dict) -> None: ...
    async def upsert_remediation(self, record: dict) -> None: ...
    async def upsert_path(self, record: dict) -> None: ...
    async def list_exposures(self, tenant_id: str) -> list[dict]: ...
    async def list_clusters(self, tenant_id: str) -> list[dict]: ...
    async def list_remediations(self, tenant_id: str) -> list[dict]: ...
    async def list_paths(self, tenant_id: str, limit: int) -> list[dict]: ...


@runtime_checkable
class ReportEventPublisher(Protocol):
    async def publish_report_generated(self, report: Report) -> None: ...
